In [1]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.ones((3,2), dtype=np.int16)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [4]:
np.empty((3,3))

array([[6.93987464e-310, 6.93987464e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [5]:
np.empty([3,3], dtype=np.int16)

array([[19336, 30761, 32704],
       [    0, 19336, 30761],
       [32704,     0,    32]], dtype=int16)

In [6]:
len(np.arange(10,25, .001))

15000

In [7]:
np.linspace(10,50)

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

In [8]:
np.linspace(10, 50, 5)

array([10., 20., 30., 40., 50.])

In [9]:
np.random.random((2,3))

array([[0.75188659, 0.97619928, 0.23810435],
       [0.96128998, 0.44979089, 0.43944546]])

In [10]:
c = np.array(((1,2,3,4,5), (6,7,8,9,10)))
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
c.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
c.reshape((5,-1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
d = np.zeros((1,5))
d

array([[0., 0., 0., 0., 0.]])

In [14]:
d

array([[0., 0., 0., 0., 0.]])

In [15]:
np.vstack((c, d))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
e = np.zeros((2,2))
e

array([[0., 0.],
       [0., 0.]])

In [17]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html
np.hstack((c, e))

array([[ 1.,  2.,  3.,  4.,  5.,  0.,  0.],
       [ 6.,  7.,  8.,  9., 10.,  0.,  0.]])

In [18]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [19]:
np.hsplit(x, 2)


[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [20]:
np.hsplit(x, np.array([3, 6]))


[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]), array([[ 3.],
        [ 7.],
        [11.],
        [15.]]), array([], shape=(4, 0), dtype=float64)]

In [25]:
x = np.arange(20.0)
np.split(x, [2, 5, 9, 15])

[array([0., 1.]),
 array([2., 3., 4.]),
 array([5., 6., 7., 8.]),
 array([ 9., 10., 11., 12., 13., 14.]),
 array([15., 16., 17., 18., 19.])]