In [1]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [8]:
np.argmax(a)

5

In [3]:
np.argmin(a)

0

In [13]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [10]:
# Find the indices of array elements that are non-zero, grouped by element.
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html
np.argwhere(a>=2)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [11]:
## Counting
## count_nonzero()
np.count_nonzero(np.array([[0,1],[1,1],[2,0]]))

4

In [12]:
a

array([[0, 1, 2],
       [3, 4, 5]])